version: "3.9"
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"

    volumes:
      - dbData:/data/db

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - dbData:/data/cache

volumes:
  dbData:
