version: "3.9"
services:
  mongodb:
    image: mongo:6.0.13-jammy
    ports:
      - "27017:27017"

    volumes:
      - dbData:/data/db

  cache:
    image: redis:7.2.4-alpine3.19
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning 
    volumes:
      - dbData:/data/cache

volumes:
  dbData:
